name = "stock-scanner"
main = "web_app.py"
compatibility_date = "2025-03-01"

[build]
command = """
pip install wheel setuptools
pip install -r requirements.txt
"""

[build.upload]
format = "service-worker" 
