name = "stock-scanner"
main = "web_app.py"
compatibility_date = "2024-03-01"
compatibility_flags = ["python_workers"]

[build]
command = """
pip install wheel setuptools
pip install -r requirements.txt
"""

# 移除不必要的上传格式配置
# [build.upload]
# format = "service-worker" 
